version: '3'

services:
  finalapp:
    image: finalapp:latest
    build:
      .
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

networks:
  backend:
    driver: bridge

