### (get all stud)
get http://localhost:3000/api/students

@token = "a0BrLmNvbToxMjM0"

### (add stud)
POST http://localhost:3000/api/addStudent
Content-Type: application/json
Authorization: Basic bW9kMUBnbWFpbC5jb206MTIzNA==

{
    "name":"krish",
    "dept":"cse",
    "year":"4",
    "regNo":"124003153"
}

### (Register)
POST http://localhost:3000/api/mod/register
Content-Type: application/json

{
    "name":"Mod1",
    "email":"mod1@gmail.com",
    "password":"1234"
}
